<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[loginInvalid: test case started]]>
    </line>
    <line>
      <![CDATA[The name of the testcase failed is: loginInvalid]]>
    </line>
    <line>
      <![CDATA[loginValid: test case started]]>
    </line>
    <line>
      <![CDATA[The name of the testcase passed is: loginValid]]>
    </line>
    <line>
      <![CDATA[tearDown: test case started]]>
    </line>
    <line>
      <![CDATA[The name of the testcase passed is: tearDown]]>
    </line>
  </reporter-output>
  <suite started-at="2020-04-30T16:52:43 IST" name="Test Suite" finished-at="2020-04-30T16:53:17 IST" duration-ms="34060">
    <groups>
    </groups>
    <test started-at="2020-04-30T16:52:43 IST" name="Execute Smoke test " finished-at="2020-04-30T16:53:17 IST" duration-ms="34060">
      <class name="seleniumTest.AppTest">
        <test-method is-config="true" signature="openUrl()[pri:0, instance:seleniumTest.AppTest@6a6afff2]" started-at="2020-04-30T16:52:43 IST" name="openUrl" finished-at="2020-04-30T16:52:54 IST" duration-ms="10916" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openUrl -->
        <test-method signature="loginInvalid()[pri:0, instance:seleniumTest.AppTest@6a6afff2]" started-at="2020-04-30T16:52:54 IST" name="loginInvalid" finished-at="2020-04-30T16:52:56 IST" duration-ms="1906" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Please check your username and password. If you still can't log in, contact your Salesforce administrator.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Please check your username and password. If you still can't log in, contact your Salesforce administrator.] but found []
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at seleniumTest.AppTest.loginInvalid(AppTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[loginInvalid: test case started]]>
            </line>
            <line>
              <![CDATA[The name of the testcase failed is: loginInvalid]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginInvalid -->
        <test-method signature="loginValid()[pri:1, instance:seleniumTest.AppTest@6a6afff2]" started-at="2020-04-30T16:52:56 IST" name="loginValid" finished-at="2020-04-30T16:53:13 IST" duration-ms="16951" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[loginValid: test case started]]>
            </line>
            <line>
              <![CDATA[The name of the testcase passed is: loginValid]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginValid -->
        <test-method signature="tearDown()[pri:2, instance:seleniumTest.AppTest@6a6afff2]" started-at="2020-04-30T16:53:13 IST" name="tearDown" finished-at="2020-04-30T16:53:17 IST" duration-ms="4217" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[tearDown: test case started]]>
            </line>
            <line>
              <![CDATA[The name of the testcase passed is: tearDown]]>
            </line>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- seleniumTest.AppTest -->
    </test> <!-- Execute Smoke test  -->
  </suite> <!-- Test Suite -->
</testng-results>
